### PR TITLE
Everything docker-related works now.

### PR DESCRIPTION
**Pull request by HarshaVardhanJ**
- Have cleaned up the documentation and added a link in the README which points to the Docker-related documentation.
- Fixed errors in `entrypoint.sh` and compose files.
- The demo on Play With Docker works now. Users have a way to use the demo without having to spin up their own instance. Look at the `Demo` section in `Docker.md` for more information.
- Large additions to `entrypoint.sh` which takes care of performing liveness probes on Elasticsearch prior to starting Archivy. This ensures that Archivy will not be started until Elasticsearch is serving requests, provided the `ELASTICSEARCH_ENABLED` variable is set to `1`.
- Changes to Dockerfiles to accommodate the aforementioned change to `entrypoint.sh` .
- Fixed labels in Dockerfiles.

**EDIT** (25th Aug, 2020):
*Revised list of changes below*

* Documentation is up-to-date and has replaced the old `README.md` file. 
* `entrypoint.sh` is now compatible with `sh`, and does not need `bash` to run.
* `entrypoint.sh` includes a 'health check' in order to verify if Elasticsearch is up and running at the URL defined in the variable `ELASTICSEARCH_URL`, **if and only if** `ELASTICSEARCH_ENABLED=1`. The script will wait until it is able to establish a connection @ `ELASTICSEARCH_URL` before running `archivy`.
* `local-build.Dockerfile` has been removed. The corresponding `docker-compose-local-build.yml` has also been removed.
* The new Dockerfile builds a significantly smaller and more secure container image by
  * Leveraging multi-stage builds in order to reduce final image size by 2.5 times when compared to the old image(from 161MB to 60MB).
  * Running `archivy` as non-root user inside the container.
* Have removed all unnecessary files(old source code). This branch now contains files pertaining only to Docker.

### CODE REVIEW

**Comment by HUAWEI-B315-32A7** [comment]
Have cleaned up the documentation and added a link in the README which points to the Docker-related documentation.
Fixed errors in entrypoint.sh and compose files.
The demo on Play With Docker works now. Users have a way to use the demo without having to spin up their own instance. Look at the Demo section in Docker.md for more information.
Large additions to entrypoint.sh which takes care of performing liveness probes on Elasticsearch prior to starting Archivy. This ensures that Archivy will not be started until Elasticsearch is serving requests, provided the ELASTICSEARCH_ENABLED variable is set to 1.
Changes to Dockerfiles to accommodate the aforementioned change to entrypoint.sh .
Fixed labels in Dockerfiles.
You can view, comment on, or merge this pull request online at:

  https://github.com/Uzay-G/archivy/pull/24

Commit Summary

Added documentation for Docker. Other changes too
Fixed issues with entrypoint and compose files
Major additions to entrypoint.sh
Merge branch 'docker' of https://github.com/Uzay-G/archivy into docker
Changed link to compose file in Play With Docker link in Docker.md
Changed compose version to 3.1. Added environment variables.
Changed bind-mounted volume to use Docker named volumes.
Changed extension from 'yaml' to 'yml'. Something seems to be causing issues with Play With Docker
Changed file name in Docker.md. Will check if PWD works now.
Changed compose file version to 3.8.
Corrections and some additions to Docker.md
Fixed container image label in Dockerfiles to reflect the right branch.
Removed Docker-related content from README and added link to Docker.md file.
File Changes

A .dockerignore (6)
A Docker.md (459)
M Dockerfile (25)
M README.md (96)
D docker-compose-local-build.yaml (12)
A docker-compose-local-build.yml (18)
A docker-compose-with-elasticsearch.yml (53)
D docker-compose.yaml (9)
A docker-compose.yml (16)
M entrypoint.sh (79)
M local-build.Dockerfile (25)
Patch Links:

https://github.com/Uzay-G/archivy/pull/24.patch
https://github.com/Uzay-G/archivy/pull/24.diff
—
You are receiving this because you are subscribed to this thread.
Reply to this email directl

**Comment by HUAWEI-B315-32A7** [comment]
![Uploading 90862733...]

**Comment by HUAWEI-B315-32A7** [comment]
image

**Comment by HarshaVardhanJ** [comment]
@Uzay-G @srevinsaju Please report the 'HUAWEI-B315-32A7' user. I just did. They're posting unrelated comments in this thread.

**Comment by Uzay-G** [comment]
Thanks. I deleted his messages and reported him

**Review by Uzay-G — COMMENTED** [review]
Why have all the files been deleted? Do you not need them for the image?

Could you also please remove the mentions like `Built and maintained by ...`. You're already in the contributors list on the homepage and I'd rather not have that type of mentions in the code. Thanks :smile:.

@cktang88 Could you maybe check this pr out? I'm not very experienced with docker so it's hard for me to review, and you opened that issue about the docker-compose.

Also @HarshaVardhanJ is there an error when creating a note. We need to think about frontend editing but until then the note creation (not editing), should work.

Thanks for all of your work!

**Comment by HarshaVardhanJ** [comment]
>Why have all the files been deleted? Do you not need them for the image?

I don't need them for the image. Besides, the code in the `docker` branch was not up to date with the `master` branch. In any case, the Dockerfile now pulls version-pinned releases directly from GitHub. So there's no necessity for the code.

>Could you also please remove the mentions like Built and maintained by .... You're already in the contributors list on the homepage and I'd rather not have that type of mentions in the code. Thanks 😄.

Will do. Sorry about that. That's standard boilerplate across all my Dockerfiles. The next commit will not have that part.

>Also @HarshaVardhanJ is there an error when creating a note. We need to think about frontend editing but until then the note creation (not editing), should work.

There is no error when creating the note. But *after* the creation, when the program tries to open the note using `xdg-open`, some errors show up in stderr(but not in the browser). So the errors encountered during the attempted opening of the created note aren't visible in the browser to the user. It just shows the page where the note has been created. So, note creation works with no errors shown to the user.

**Comment by HarshaVardhanJ** [comment]
Made the changes. Ready to be pulled when you're ready.

**Comment by cktang88** [comment]
@Uzay-G this works for me locally :) Thanks @HarshaVardhanJ

**Comment by cktang88** [comment]
Closes #39

**Comment by Uzay-G** [comment]
Perfect!

**Comment by Uzay-G** [comment]
Thank you so much for your work @HarshaVardhanJ :tada:

**Comment by HarshaVardhanJ** [comment]
@cktang88 Thanks for the confirmation!

**Comment by HarshaVardhanJ** [comment]
@Uzay-G You're welcome. Happy to contribute.

**Pull request merged**
