### PR TITLE
Dockerfile for `master` created. Other changes too

### PR DESCRIPTION
**Pull request by HarshaVardhanJ**
A new Dockerfile titled `Dockerfile.source` has been added. This
Dockerfile is used to build the image from the `master` branch.

Made some improvements to `entrypoint.sh` and `healthcheck.sh`. Minor
additions to `container-structure-test.yaml`.

`Docker.md` has been added which serves as the documentation for the
image on DockerHub.

Two Github Actions files have been added. `build-on-release.yml` is used
to build, test, and push images with the appropriate versioned tags
whenever a new release is published. `build-on-push-master.yml` is used
to build, test, and push images with the `source` tag whenever a commit
is made to the code in the `master` branch. This image will be built
directly from the source code in the `master` branch.

### CODE REVIEW

**Comment by Uzay-G** [comment]
This is quite extremely thorough! Thank you so much for your effort!

You've tested these changes?

**Comment by HarshaVardhanJ** [comment]
Thank you! Happy to help.

Regarding the changes, please don't merge this yet. There's an issue with the `build-on-release.yml` and `build-on-push-master.yml`. The issue lies in the second last build stage(`dockerBuildPush`) where an image of Archivy is built for the following architectures:

* `amd64`
* `arm64`
* `arm32v6`
* `arm32v7`
* `i386`
* `s390x`

The problem is that `pandoc` is only available for `amd64`. So, the image will not build for the other architectures. This is not a bad thing per se, but it is nicer to provide images for multiple architectures as not everybody uses an `x86-64`-based CPU.

Here's what I'll do. I'll fix the `build-on-release.yml` and `build-on-push-master.yml` files to build only for `amd64` for now. In the meantime, I'll try to compile `pandoc` for the other architectures and check if I can get it working.

**Comment by HarshaVardhanJ** [comment]
Just made a commit. Now the images will build only for `amd64` platforms.

**Comment by HarshaVardhanJ** [comment]
You can merge this PR now.

**Review by Uzay-G — APPROVED** [review]
:+1:

**Comment by Uzay-G** [comment]
@HarshaVardhanJ could you check this out: https://github.com/Uzay-G/archivy/actions/runs/285659797. I moved the workflows that interacted with `master` into the master branch and left the other one in the `docker` one.

**Comment by HarshaVardhanJ** [comment]
> @HarshaVardhanJ could you check this out: https://github.com/Uzay-G/archivy/actions/runs/285659797. I moved the workflows that interacted with `master` into the master branch and left the other one in the `docker` one.

Looks fine to me.

**Pull request merged**
