### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by HarshaVardhanJ**

### CODE REVIEW

**Comment by HarshaVardhanJ** [comment]
Dockerfile for building container images of Archivy. People can use this to build their own images by just downloading the Dockerfile. They don't need to clone the whole repository.

**Comment by Uzay-G** [comment]
Amazing! Could you provide instructions for running the image in the Setup part of the README?

Thank you so much :)

**Comment by HarshaVardhanJ** [comment]
Will do. Just fixed an error that I'd made in the Dockerfile.

**Comment by Uzay-G** [comment]
Alright! Nice :)

**Pull request merged**
