### PR TITLE
Login system

### PR DESCRIPTION
**Pull request by Uzay-G**
Contributes to https://github.com/Uzay-G/archivy/issues/19.

This pr adds login functionality like this:

random

This is a work in progress and I plan on adding configuration so you can allow people to view and maybe not edit the knowledge base, or add users to your knowledge base and give them access. This is not an easy task but it's the goal.

### CODE REVIEW

**Comment by Uzay-G** [comment]
@srevinsaju @HarshaVardhanJ could you try testing this out and providing feedback? That'd be awesome :+1:

**Comment by srevinsaju** [comment]
Sure, I can test it tomorrow. Looks cool!

**Comment by srevinsaju** [comment]
Tested, its been a quite while since I tested, but, on a fresh virtual environment, this is what I see
image

Looks like the styles are missing.

**Comment by srevinsaju** [comment]
After logging in, the styles work
image

**Comment by Uzay-G** [comment]
Oh ik why - I'll take care of it.

**Comment by srevinsaju** [comment]
Great! Tested the rest. works cool :tada:

**Comment by srevinsaju** [comment]
#106 aims to be merged to this PR, before this PR is merged, if it looks appropriate :smile:

**Comment by Uzay-G** [comment]
That issue should be fixed now - is it good?

**Comment by srevinsaju** [comment]
Ok let me pull and test again

**Comment by srevinsaju** [comment]
Looks good. Tested :tada:

**Comment by Uzay-G** [comment]
Merging this for now. I will add the multi-user system in a later release.

**Pull request merged**
