### PR TITLE
Remove redundant / branched requirements.txt

### PR DESCRIPTION
**Pull request by srevinsaju**
The requirements.txt required some modules which was not directly used within
archivy. Some requirements are the direct dependencies of the dependencies.
Pinned versions on requirements sometimes creates conflicts on end-users's pip
installation. For example, importlib_metadata==1.6.0 has a buggy pkg_resources.DistributionNotFound , which is now fixed in importlib_metadata==1.7.0

### CODE REVIEW

**Comment by Uzay-G** [comment]
Nice! I was looking for something like this to trim the requirements.txt. Does this work for you locally (with only having installed these dependencies).

**Comment by srevinsaju** [comment]
I will just confirm this in few minutes.

**Comment by srevinsaju** [comment]
@Uzay-G the appimage I provided you includes only the requirements provided in this patch. So, if the appimage works perfectly, you can merge this PR

**Review by Uzay-G — APPROVED** [review]
Nice! Ill merge :tada:

**Pull request merged**
