### PR TITLE
Added documentation for Docker. Other changes too

### PR DESCRIPTION
**Pull request by HarshaVardhanJ**
Added a `.dockerignore` file which is useful when building images
locally. The files in `.dockerignore` will not be sent to the Docker
daemon during build time, thereby making the final image smaller.

Added `Docker.md` which is going to be the source of all documentation
for Archivy pertaining to containers.

Have added a few lines in `Dockerfile` to get rid of some of the large,
unnecessary repository files like `archivy.gif` and other documentation
files which are not needed for running Archivy inside the container.

Have removed the title comments from the compose files. This causes
erros with 'Play With Docker'.

Have added a compose file `docker-compose-with-elasticsearch.yaml` which
takes care of setting up Archivy with Elasticsearch.

### CODE REVIEW

**Comment by HarshaVardhanJ** [comment]
@Uzay-G I've added the documentation with this PR amongst other changes which is detailed in the commit message.

**Comment by Uzay-G** [comment]
Wow very nice! Could you remove the docker docs in the README and make it link to DOCKER.md?

This is very detailed but we're starting to accumulate many different docker files in our root dir and it might confuse new users. Is there a way we can either concentrate the files or localize them in a subdir?

**Comment by HarshaVardhanJ** [comment]
Will do. I had the same thought today about segregating all Docker/container related files into one folder. If I moved the Dockerfiles into a directory, I'll need to make some changes in the `local-build.Dockerfile` as it depends on having all source code in the same directory.

By the way, I'm running into some issues with Archivy starting before Elasticsearch due to which it is unable to connect with it. In the current commits, this issue is unresolved. Don't merge this PR yet, I'll try to fix the issue by either adding check to the `entrypoint.sh` file or by making some changes to the compose files. Thank you for your patience.

**Comment by Uzay-G** [comment]
>

Alright. I think we should solve this by moving docker-related files to a new docker branch at least until everything is sorted out.
I can work on this migration to a new branch. Would that be good with you?

**Comment by HarshaVardhanJ** [comment]
Sounds good.

**Comment by Uzay-G** [comment]
I'll close this pr now so that we can make it merge into the `docker` branch.

**Pull request closed without merging**
