### PR TITLE
Removed duplicate actions files. Updated `Docker.md` and its template.

### PR DESCRIPTION
**Pull request by HarshaVardhanJ**
Both Github actions files had the same error, namely a dependence on the job `ContainerTestScan`(which does not exist, but is instead named `ContainerTestAndScan`). Have fixed this error.

### CODE REVIEW

**Comment by HarshaVardhanJ** [comment]
@Uzay-G There's an error in the Github Actions files which I've fixed. Please update them in the `master` branch.

**Comment by Uzay-G** [comment]
For the github actions that are run on master, could you simply make the pr to master instead of adding them on the `docker` branch? It would be better.

**Comment by Uzay-G** [comment]
I'll merge those actions to master to keep things cleaner so we don't have to maintain two identical files on different branches.

**Comment by HarshaVardhanJ** [comment]
Have created a PR to the `master` branch.

**Comment by HarshaVardhanJ** [comment]
You can merge this now. I've removed 3 of the actions files that have duplicates.

**Pull request merged**
