### PR TITLE
Added the dark mode

### LINKED ISSUE #89: Other colour themes (dark)
Look into the enabling other colour themes.

### PR DESCRIPTION
**Pull request by bislara**
Added dark mode for the application.
There is a button in the right corner which gives the option to toggle from dark mode to white mode. 

Fixed #89 

image

### CODE REVIEW

**Comment by Uzay-G** [comment]
I find the sidebar somewhat weird and there are many different, somewhat clashing colors. The rest looks good but isn't it overkill to load this js lib? Can we customize the colors?

Otherwise specifying our own css could be nice.

**Comment by bislara** [comment]
Okay, give me some time. I will try something and let you know about it.

**Comment by Uzay-G** [comment]
Okay thanks!

**Comment by bislara** [comment]
@Uzay-G  do check this once now. I did the dark mode only using the css

**Comment by bislara** [comment]
image

image

**Comment by Uzay-G** [comment]
Thanks for your work! I've started reviewing it and will make a few changes!

**Comment by Uzay-G** [comment]
@bislara sorry I made a mistake with git. One second.

**Comment by Uzay-G** [comment]
@bislara I made a few edits and messed up your branch up by accident. Could you please open a new pr from this branch I made? https://github.com/Uzay-G/archivy/bislara_dark. I'll merge it after :+1:

**Comment by bislara** [comment]
Okay sure. No problem. I am doing it.

**Comment by bislara** [comment]
Done. Check this out [https://github.com/Uzay-G/archivy/pull/111](https://github.com/Uzay-G/archivy/pull/111)

**Pull request closed without merging**
